--FIELDS  USERDOC_SEQ, USERDOC_SERIES, USERDOC_NBR, IND_IMPORT, USERDOC_TYPE, LAW_CODE, FILING_DATE, RECEPTION_DATE, NOTES, PERSON_NAME  , NATIONALITY_COUNTRY_CODE, RESIDENCE_COUNTRY_CODE, ADDRESS_STREET, CAPTURE_USER_ID, CAPTURE_DATE  ;;
--QUERY 
SELECT userdoc_seq,USERDOC_SERIES,USERDOC_NBR,IND_IMPORT, userdoc_type,LAW_CODE,FILING_DATE,RECEPTION_DATE,NOTES,
PERSON_NAME,NATIONALITY_COUNTRY_CODE,RESIDENCE_COUNTRY_CODE ,ADDRESS_STREET,CAPTURE_USER_ID,CAPTURE_DATE  
FROM vw_userdoc where userdoc_type is not null and filing_date is not null;;